image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

before_script:
    - dotnet --version

build_model:
    stage: build
    script:
        - dotnet build WeShallNotPass.Model

build_view:
    stage: build
    image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019
    tags: [windows]
    script:
        - dotnet build WeShallNotPass.sln

test_model:
    stage: test
    script:
        - dotnet test WeShallNotPass.Test
